config/routes.rb
Rails.application.routes.draw do
  get 'control/index'

  devise_for :usuarios
  resources :empresas
  resources :myrfcs
  resources :listrfcs
  resources :profile_lists
  resources :user_apps

  resources :credits
  get 'charges/index'

  post 'charges/create'

  get 'charges/show'

  get 'home' => 'myrfcs#index', as: :inicio
  get '/home/:id' =>  'myrfcs#show', as: :show

  resources :myrfcs
  resources :empresas
  resources :listrfcs
  namespace :api do
    namespace :v1 do
      resources :get_profile_list, path: "personal_data"
      resources :get_rfc_list, path: "rfc"
      resources :get_comercio, path: "comercio"
      resources :get_rfc_id, path: "rfc_id"
      resources :get_personal_id, path: "personal_id"
      resources :delete_personal_id, path: "delete_personal"
      resources :delete_rfc_id, path: "delete_rfc"
      resources :compartir_rfc, path: "compartir_rfc"
      resources :crear_personal_data, path: "crear_personal_data"
      resources :crear_rfc, path: "crear_rfc"
      resources :get_user_app, path: "get_user"
      resources :crear_user_app, path: "create_user"
      resources :get_rfc, path: "myrfcs"

      

    end
  end

  root 'control#index'

end

app/models/myrfc.rb
class Myrfc < ActiveRecord::Base
	def to_param
    "#{id}-#{rfc}"
  end
end

app/controllers/myrfcs_controller.rb
class MyrfcsController < ApplicationController
  before_action :set_myrfc, only: [:show, :edit, :update, :destroy]

  # GET /myrfcs
  # GET /myrfcs.json

  def index
    @name = Empresa.where(:user_id => current_usuario.id).pluck(:name).first
    @empresa = Empresa.where(:user_id => current_usuario.id).pluck(:comercio_id).first
    @myrfcs = Myrfc.where(:comercio_id => @empresa).order(created_at: :desc)

  end

  # GET /myrfcs/1
  # GET /myrfcs/1.json
  def show
    @myrfcs = Myrfc.where(:id => params[:id]).pluck(:comercio_id).first
    @empresa = Empresa.where(:comercio_id => @myrfcs).pluck(:user_id).first

    if @empresa.to_i == current_usuario.id
      else
      render json: {message: "Url no existe o no tienes acceso"}
    end
  end

  # GET /myrfcs/new
  def new
    @myrfc = Myrfc.new
  end

  # GET /myrfcs/1/edit
  def edit
  end

  # POST /myrfcs
  # POST /myrfcs.json
  def create
    @myrfc = Myrfc.new(myrfc_params)

    respond_to do |format|
      if @myrfc.save
        format.html { redirect_to @myrfc, notice: 'Myrfc was successfully created.' }
        format.json { render :show, status: :created, location: @myrfc }
      else
        format.html { render :new }
        format.json { render json: @myrfc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myrfcs/1
  # PATCH/PUT /myrfcs/1.json
  def update
    respond_to do |format|
      if @myrfc.update(myrfc_params)
        format.html { redirect_to @myrfc, notice: 'Myrfc was successfully updated.' }
        format.json { render :show, status: :ok, location: @myrfc }
      else
        format.html { render :edit }
        format.json { render json: @myrfc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myrfcs/1
  # DELETE /myrfcs/1.json
  def destroy
    @myrfc.destroy
    respond_to do |format|
      format.html { redirect_to myrfcs_url, notice: 'Myrfc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myrfc
      @myrfc = Myrfc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myrfc_params
      params.require(:myrfc).permit(:name, :rfc, :address, :phone, :email, :cp, :comercio_id, :referencia)
    end
end

app/helpers/myrfcs_helper.rb
module MyrfcsHelper
end

app/views/myrfcs/_form.html.erb
<%= form_for(@myrfc) do |f| %>
  <% if @myrfc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myrfc.errors.count, "error") %> prohibited this myrfc from being saved:</h2>

      <ul>
      <% @myrfc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rfc %><br>
    <%= f.text_field :rfc %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cp %><br>
    <%= f.text_field :cp %>
  </div>
  <div class="field">
    <%= f.label :comercio_id %><br>
    <%= f.text_field :comercio_id %>
  </div>
  <div class="field">
    <%= f.label :referencia %><br>
    <%= f.text_field :referencia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myrfcs/edit.html.erb
<h1>Editing Myrfc</h1>

<%= render 'form' %>

<%= link_to 'Show', @myrfc %> |
<%= link_to 'Back', myrfcs_path %>

app/views/myrfcs/index.html.erb
<style type="text/css">
.nav{
  /* Rectangle 1: */
background: #FFFFFF;
border: 1px solid #D9E3F0;
top: 0px;
height: 80px;
}
.session{
  /* Has iniciado sesión : */
    font-family: Helvetica;
    font-size: 12px;
    color: #697689;
    line-height: 14px;
    position: relative;
    left: 65%;
    top:14px;
}
.column_left{
  /* Left_column: */
  background: #FFFFFF;
  border-left: 0;
  border-top: 0;
  border-right: 1px;
  border-style: solid;
  border-color: #D9E3F0;
  position: relative;
  float: left;
  width: 20%;
  height:100vh;
}
.column_right{
  /* Left_column: */
  background: #FFFFFF;
    border-left: 1px;
  border-top: 0;
  border-right: 0;
  border-style: solid;
  border-color: #D9E3F0;
  float: right;
  width: 100%;
  height:100vh;
}
.empresa{
  /* Pepe Pizza SA de CV: */
font-family: Helvetica;
font-size: 38px;
color: #697689;
line-height: 58px;
margin-left: 10px;
}
.subtitulo{
/* Listado de Datos: */
font-family: AvenirNext-DemiBold;
font-size: 36px;
color: #2CCCE4;
line-height: 49px;
margin-left: 10px;
}
.borde_table{
/* Rectangle 8: */
background: #FFFFFF;
border: 1px solid #D9E3F0;
margin-left: 10px;
width: 100%;
}
.text_table_head{
  /* Nombre o razón socia: */
font-family: Helvetica;
font-size: 14px;
color: #697689;
line-height: 17px;


}
.celda{
/* Rectangle 8: */
background: #FFFFFF;
border: 1px solid #D9E3F0;
padding: 20px;
}
.celda_contenido{
    font-family: Helvetica;
    font-size: 12px;
    color: #697689;
    line-height: 14px;
    padding: 10px;
}
</style>

<div class="nav">
<p class="navbar-text pull-right">
<% if usuario_signed_in? %>
      <span class="session">Has iniciado sesión como <strong><%= current_usuario.email %></strong>.
        <%= link_to 'Edit profile', edit_usuario_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_usuario_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_usuario_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_usuario_session_path, :class => 'navbar-link'  %>
      <% end %>
     </span>
</div>
<div>
<div class="column_right">
  <span class="empresa"><%= @name %> -- Comercio ID: <%= @empresa %></span>
<div class="subtitulo">Solicitudes de Facturas</div>

<table class="borde_table">
  <thead class="text_table_head">
    <tr>
      <th class="celda">Nombre o Razón Social</th>
      <th class="celda">Rfc</th>
      <th class="celda">Dirección</th>
      <th class="celda">Teléfono</th>
      <th class="celda">Email</th>
      <th class="celda">Código Postal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @myrfcs.each do |myrfc| %>
      <tr>
        <td class="celda_contenido"><%= myrfc.name %> -- <%= time_ago_in_words(myrfc.created_at) %></td>
        <td class="celda_contenido"><%= myrfc.rfc %></td>
        <td class="celda_contenido"><%= myrfc.address %></td>
        <td class="celda_contenido"><%= myrfc.phone %></td>
        <td class="celda_contenido"><%= myrfc.email %></td>
        <td class="celda_contenido"><%= myrfc.cp %></td>
        <td ><%= link_to 'Copiar', show_path(:id => myrfc.id)%></td>
        <td><%= link_to 'Eliminar', myrfc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/myrfcs/new.html.erb
<h1>New Myrfc</h1>

<%= render 'form' %>

<%= link_to 'Back', myrfcs_path %>

app/views/myrfcs/show.html.erb
<style type="text/css">
.textbox{
  /* Base: */
    background: #FFFFFF;
    border: 4px solid #D6DEE9;
    border-radius: 10px;
    /* Eje. Pizzas el bajío: */
    font-family: AvenirNext-Regular;
    font-size: 20px;
    color: #B2BCCA;
    letter-spacing: 0.53px;
    line-height: 45px;
    padding: 3px;
    width: 400px;

}
.textbox:focus{
  /* Base: */
    border: 4px solid #2CCCE4;
    border-radius: 10px;
    /* Typed Text: */
    font-family: AvenirNext-Regular;
    font-size: 20px;
    color: #697689;
    letter-spacing: 0.53px;
    line-height: 45px;
}
.nav{
  /* Rectangle 1: */
    background: #FFFFFF;
    border: 1px solid #D9E3F0;
    top: 0px;
    height: 80px;
}
.session{
  /* Has iniciado sesión : */
    font-family: Helvetica;
    font-size: 12px;
    color: #697689;
    line-height: 14px;
    position: relative;
    left: 65%;
    top:14px;
}
.text{
    /* Nombre corto.: */
    font-family: Helvetica;
    font-size: 18px;
    color: #697689;
    line-height: 29px;
    text-align: center;

}
.header{
  /* Rectangle 3: */
background: #2CCCE4;
border: 1px solid #2CCCE4;
margin-bottom: 10px;
}
.text_head{
  /* Configuración del ne: */
font-family: Helvetica;
font-size: 40px;
color: #697689;
line-height: 58px;
text-align: center;
margin-bottom: 20px;
}
.button{
  /* Base: */
background: #37D67A;
border-radius: 8px;
/* Button: */
font-family: AvenirNext-DemiBold;
font-size: 20px;
color: #FFFFFF!important;
letter-spacing: 0.5px;
line-height: 41px;
border: none;
right: 0px;
padding: 10px;
text-decoration: none;
float: left;

}
.button:hover{
  opacity: .75;
  background: #37D67A;
}
.container{
  position: relative;
  padding-left: 35%;
}
.label{
    /* Typed Text: */
  font-family: AvenirNext-Regular;
  font-size: 20px;
  color: #697689;
  letter-spacing: 0.53px;
  line-height: 20px;
}
.label_copy{
/* Typed Text: */
font-family: AvenirNext-Regular;
font-size: 18px;
color: #697689;
letter-spacing: 0.53px;
line-height: 20px;
width: 50%;
}
.label_copy:hover{
  background-color: #697689;
  color: white;
  width: 50%;
  padding: 5px;
  border-radius: 5px;
  border-style: solid;
  border-color: #FFA69E;
}

</style>
<div class="nav">
<p class="navbar-text pull-right">
<% if usuario_signed_in? %>
      <span class="session">Has iniciado sesión como <strong><%= current_usuario.email %></strong>.
        <%= link_to 'Edit profile', edit_usuario_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_usuario_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_usuario_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_usuario_session_path, :class => 'navbar-link'  %>
      <% end %>
     </span>
</div>
<div class="header"></div>
<div class="text_head">¡Listo para copiar la información!</div>

<div class="container">
<p id="notice"><%= notice %></p>
<p>
  <span class="label">Nombre:</span>
  <span class="label_copy"><%= @myrfc.name %></span>
</p>
<p>
  <span class="label">Rfc:</span>
  <span class="label_copy"><%= @myrfc.rfc %></span>
</p>

<p>
  <span class="label">Dirección:</span>
  <span class="label_copy"><%= @myrfc.address %></span>
</p>

<p>
  <span class="label">Telefono:</span>
  <span class="label_copy"><%= @myrfc.phone %></span>
</p>

<p>
  <span class="label">Correo Electronico:</span>
  <span class="label_copy"><%= @myrfc.email %></span>
</p>

<p>
  <span class="label">Código postal:</span>
  <span class="label_copy"><%= @myrfc.cp %></span>
</p>

<p>
  <span class="label">Comercio:</span>
  <span class="label_copy"><%= @myrfc.comercio_id %></span>
</p>

<p>
  <span class="label">Referencia:</span>
  <span class="label_copy"><%= @myrfc.referencia %></span>
</p>
<%= link_to 'Regresar a listado', inicio_path, :class => "button" %>
</div>