config/routes.rb
Rails.application.routes.draw do
  get 'control/index'

  devise_for :usuarios
  resources :empresas
  resources :myrfcs
  resources :listrfcs
  resources :profile_lists
  resources :user_apps

  resources :credits
  get 'charges/index'

  post 'charges/create'

  get 'charges/show'

  get 'home' => 'myrfcs#index', as: :inicio
  get '/home/:id' =>  'myrfcs#show', as: :show

  resources :myrfcs
  resources :empresas
  resources :listrfcs
  namespace :api do
    namespace :v1 do
      resources :get_profile_list, path: "personal_data"
      resources :get_rfc_list, path: "rfc"
      resources :get_comercio, path: "comercio"
      resources :get_rfc_id, path: "rfc_id"
      resources :get_personal_id, path: "personal_id"
      resources :delete_personal_id, path: "delete_personal"
      resources :delete_rfc_id, path: "delete_rfc"
      resources :compartir_rfc, path: "compartir_rfc"
      resources :crear_personal_data, path: "crear_personal_data"
      resources :crear_rfc, path: "crear_rfc"
      resources :get_user_app, path: "get_user"
      resources :crear_user_app, path: "create_user"
      resources :get_rfc, path: "myrfcs"

      

    end
  end

  root 'control#index'

end

app/models/user_app.rb
class UserApp < ActiveRecord::Base
end

app/controllers/user_apps_controller.rb
class UserAppsController < ApplicationController
  before_action :set_user_app, only: [:show, :edit, :update, :destroy]

  # GET /user_apps
  # GET /user_apps.json
  def index
    @user_apps = UserApp.all
  end

  # GET /user_apps/1
  # GET /user_apps/1.json
  def show
  end

  # GET /user_apps/new
  def new
    @user_app = UserApp.new
  end

  # GET /user_apps/1/edit
  def edit
  end

  # POST /user_apps
  # POST /user_apps.json
  def create
    @user_app = UserApp.new(user_app_params)

    respond_to do |format|
      if @user_app.save
        format.html { redirect_to @user_app, notice: 'User app was successfully created.' }
        format.json { render :show, status: :created, location: @user_app }
      else
        format.html { render :new }
        format.json { render json: @user_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_apps/1
  # PATCH/PUT /user_apps/1.json
  def update
    respond_to do |format|
      if @user_app.update(user_app_params)
        format.html { redirect_to @user_app, notice: 'User app was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_app }
      else
        format.html { render :edit }
        format.json { render json: @user_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_apps/1
  # DELETE /user_apps/1.json
  def destroy
    @user_app.destroy
    respond_to do |format|
      format.html { redirect_to user_apps_url, notice: 'User app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_app
      @user_app = UserApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_app_params
      params.require(:user_app).permit(:uuid_phone)
    end
end

app/helpers/user_apps_helper.rb
module UserAppsHelper
end

app/views/user_apps/_form.html.erb
<%= form_for(@user_app) do |f| %>
  <% if @user_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_app.errors.count, "error") %> prohibited this user_app from being saved:</h2>

      <ul>
      <% @user_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid_phone %><br>
    <%= f.text_field :uuid_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_apps/edit.html.erb
<h1>Editing User App</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_app %> |
<%= link_to 'Back', user_apps_path %>

app/views/user_apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Apps</h1>

<table>
  <thead>
    <tr>
      <th>Uuid phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_apps.each do |user_app| %>
      <tr>
        <td><%= user_app.uuid_phone %></td>
        <td><%= link_to 'Show', user_app %></td>
        <td><%= link_to 'Edit', edit_user_app_path(user_app) %></td>
        <td><%= link_to 'Destroy', user_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User app', new_user_app_path %>

app/views/user_apps/new.html.erb
<h1>New User App</h1>

<%= render 'form' %>

<%= link_to 'Back', user_apps_path %>

app/views/user_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid phone:</strong>
  <%= @user_app.uuid_phone %>
</p>

<%= link_to 'Edit', edit_user_app_path(@user_app) %> |
<%= link_to 'Back', user_apps_path %>