config/routes.rb
Rails.application.routes.draw do
  get 'control/index'

  devise_for :usuarios
  resources :empresas
  resources :myrfcs
  resources :listrfcs
  resources :profile_lists
  resources :user_apps

  resources :credits
  get 'charges/index'

  post 'charges/create'

  get 'charges/show'

  get 'home' => 'myrfcs#index', as: :inicio
  get '/home/:id' =>  'myrfcs#show', as: :show

  resources :myrfcs
  resources :empresas
  resources :listrfcs
  namespace :api do
    namespace :v1 do
      resources :get_profile_list, path: "personal_data"
      resources :get_rfc_list, path: "rfc"
      resources :get_comercio, path: "comercio"
      resources :get_rfc_id, path: "rfc_id"
      resources :get_personal_id, path: "personal_id"
      resources :delete_personal_id, path: "delete_personal"
      resources :delete_rfc_id, path: "delete_rfc"
      resources :compartir_rfc, path: "compartir_rfc"
      resources :crear_personal_data, path: "crear_personal_data"
      resources :crear_rfc, path: "crear_rfc"
      resources :get_user_app, path: "get_user"
      resources :crear_user_app, path: "create_user"
      resources :get_rfc, path: "myrfcs"

      

    end
  end

  root 'control#index'

end

app/models/profile_list.rb
class ProfileList < ActiveRecord::Base
end

app/controllers/profile_lists_controller.rb
class ProfileListsController < ApplicationController
  before_action :set_profile_list, only: [:show, :edit, :update, :destroy]

  # GET /profile_lists
  # GET /profile_lists.json
  def index
    @profile_lists = ProfileList.all
  end

  # GET /profile_lists/1
  # GET /profile_lists/1.json
  def show
  end

  # GET /profile_lists/new
  def new
    @profile_list = ProfileList.new
  end

  # GET /profile_lists/1/edit
  def edit
  end

  # POST /profile_lists
  # POST /profile_lists.json
  def create
    @profile_list = ProfileList.new(profile_list_params)

    respond_to do |format|
      if @profile_list.save
        format.html { redirect_to @profile_list, notice: 'Profile list was successfully created.' }
        format.json { render :show, status: :created, location: @profile_list }
      else
        format.html { render :new }
        format.json { render json: @profile_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile_lists/1
  # PATCH/PUT /profile_lists/1.json
  def update
    respond_to do |format|
      if @profile_list.update(profile_list_params)
        format.html { redirect_to @profile_list, notice: 'Profile list was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile_list }
      else
        format.html { render :edit }
        format.json { render json: @profile_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_lists/1
  # DELETE /profile_lists/1.json
  def destroy
    @profile_list.destroy
    respond_to do |format|
      format.html { redirect_to profile_lists_url, notice: 'Profile list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile_list
      @profile_list = ProfileList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_list_params
      params.require(:profile_list).permit(:full_name, :phone, :email, :birthday, :address, :city, :state, :country, :cp,:uuid_phone)
    end
end

app/helpers/profile_lists_helper.rb
module ProfileListsHelper
end

app/views/profile_lists/_form.html.erb
<%= form_for(@profile_list) do |f| %>
  <% if @profile_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile_list.errors.count, "error") %> prohibited this profile_list from being saved:</h2>

      <ul>
      <% @profile_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :cp %><br>
    <%= f.text_field :cp %>
  </div>
  <div class="field">
    <%= f.label :uuid_phone %><br>
    <%= f.text_field :uuid_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profile_lists/edit.html.erb
<h1>Editing Profile List</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile_list %> |
<%= link_to 'Back', profile_lists_path %>

app/views/profile_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profile Lists</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Birthday</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Cp</th>
      <th>uuid_phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profile_lists.each do |profile_list| %>
      <tr>
        <td><%= profile_list.full_name %></td>
        <td><%= profile_list.phone %></td>
        <td><%= profile_list.email %></td>
        <td><%= profile_list.birthday %></td>
        <td><%= profile_list.address %></td>
        <td><%= profile_list.city %></td>
        <td><%= profile_list.state %></td>
        <td><%= profile_list.country %></td>
        <td><%= profile_list.cp %></td>
        <td><%= profile_list.uuid_phone %></td>
        <td><%= link_to 'Show', profile_list %></td>
        <td><%= link_to 'Edit', edit_profile_list_path(profile_list) %></td>
        <td><%= link_to 'Destroy', profile_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile list', new_profile_list_path %>

app/views/profile_lists/new.html.erb
<h1>New Profile List</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_lists_path %>

app/views/profile_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @profile_list.full_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile_list.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile_list.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile_list.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile_list.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile_list.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile_list.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile_list.country %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @profile_list.cp %>
</p>
<p>
  <strong>Uuid_phone</strong>
  <%= @profile_list.uuid_phone %>
</p>

<%= link_to 'Edit', edit_profile_list_path(@profile_list) %> |
<%= link_to 'Back', profile_lists_path %>