config/routes.rb
Rails.application.routes.draw do
  get 'control/index'

  devise_for :usuarios
  resources :empresas
  resources :myrfcs
  resources :listrfcs
  resources :profile_lists
  resources :user_apps

  resources :credits
  get 'charges/index'

  post 'charges/create'

  get 'charges/show'

  get 'home' => 'myrfcs#index', as: :inicio
  get '/home/:id' =>  'myrfcs#show', as: :show

  resources :myrfcs
  resources :empresas
  resources :listrfcs
  namespace :api do
    namespace :v1 do
      resources :get_profile_list, path: "personal_data"
      resources :get_rfc_list, path: "rfc"
      resources :get_comercio, path: "comercio"
      resources :get_rfc_id, path: "rfc_id"
      resources :get_personal_id, path: "personal_id"
      resources :delete_personal_id, path: "delete_personal"
      resources :delete_rfc_id, path: "delete_rfc"
      resources :compartir_rfc, path: "compartir_rfc"
      resources :crear_personal_data, path: "crear_personal_data"
      resources :crear_rfc, path: "crear_rfc"
      resources :get_user_app, path: "get_user"
      resources :crear_user_app, path: "create_user"
      resources :get_rfc, path: "myrfcs"

      

    end
  end

  root 'control#index'

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    if usuario_signed_in? 
    @empresa = Empresa.where(:user_id => current_usuario.id).pluck(:id)
    if @empresa.blank?
      redirect_to '/empresas/new'
    else
      redirect_to '/home'
    end
  else
  end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)
      if @empresa.save
        redirect_to '/home'
      else
      end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:name, :razon, :user_id, :comercio_id)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<style type="text/css">
.textbox{
  /* Base: */
    background: #FFFFFF;
    border: 4px solid #D6DEE9;
    border-radius: 10px;
    /* Eje. Pizzas el bajío: */
    font-family: AvenirNext-Regular;
    font-size: 20px;
    color: #B2BCCA;
    letter-spacing: 0.53px;
    line-height: 45px;
    padding: 3px;
    width: 400px;

}
.textbox:focus{
  /* Base: */
    border: 4px solid #2CCCE4;
    border-radius: 10px;
    /* Typed Text: */
    font-family: AvenirNext-Regular;
    font-size: 20px;
    color: #697689;
    letter-spacing: 0.53px;
    line-height: 45px;
}
.nav{
  /* Rectangle 1: */
    background: #FFFFFF;
    border: 1px solid #D9E3F0;
    top: 0px;
    height: 80px;
}
.session{
  /* Has iniciado sesión : */
    font-family: Helvetica;
    font-size: 12px;
    color: #697689;
    line-height: 14px;
    position: relative;
    left: 65%;
    top:14px;
}
.text{
    /* Nombre corto.: */
    font-family: Helvetica;
    font-size: 18px;
    color: #697689;
    line-height: 29px;
    text-align: center;

}
.header{
  /* Rectangle 3: */
background: #2CCCE4;
border: 1px solid #2CCCE4;
margin-bottom: 10px;
}
.text_head{
  /* Configuración del ne: */
font-family: Helvetica;
font-size: 40px;
color: #697689;
line-height: 58px;
text-align: center;
margin-bottom: 20px;
}
.button{
  /* Base: */
background: #37D67A;
border-radius: 8px;
/* Button: */
font-family: AvenirNext-DemiBold;
font-size: 20px;
color: #FFFFFF;
letter-spacing: 0.5px;
line-height: 41px;
border: none;
right: 0px;
padding: 10px;
}
.button:hover{
  opacity: .75;
}
form{
  position: relative;
  padding-left: 35%;
}

</style>
<div class="header"></div>
<div class="text_head">Configuración de tu negocio</div>
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Ingresa un nombre corto" , :class => "text"%><br>
    <%= f.text_field :name, :placeholder => "Eje. Pizzas del bajío", :class=> "textbox" %>
  </div>
  <div class="field">
    <%= f.label "Ingresa tu razón social", :class => "text" %><br>
    <%= f.text_field :razon, :placeholder => "Eje. Acme SA de CV", :class=> "textbox" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_usuario.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :comercio_id ,:value => rand(5..1000000)%>
  </div>
  <div class="actions">
    <%= f.submit "Registrar negocio",:class => "button" %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Empresas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Razon</th>
      <th>User</th>
      <th>Comercio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.name %></td>
        <td><%= empresa.razon %></td>
        <td><%= empresa.user_id %></td>
        <td><%= empresa.comercio_id %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<div class="nav">
<p class="navbar-text pull-right">
<% if usuario_signed_in? %>
      <span class="session">Has iniciado sesión como <strong><%= current_usuario.email %></strong>.
        <%= link_to 'Edit profile', edit_usuario_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_usuario_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_usuario_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_usuario_session_path, :class => 'navbar-link'  %>
      <% end %>
     </span>
</div>

<%= render 'form' %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @empresa.name %>
</p>

<p>
  <strong>Razon:</strong>
  <%= @empresa.razon %>
</p>

<p>
  <strong>User:</strong>
  <%= @empresa.user_id %>
</p>

<p>
  <strong>Comercio:</strong>
  <%= @empresa.comercio_id %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>